name: CI/CD for WiseCow App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/sandyzayn/wisecow-app:${{ github.sha }} .

    - name: Test basic commands
      run: |
        # Test with error handling
        docker run --rm ghcr.io/sandyzayn/wisecow-app:${{ github.sha }} which cowsay || echo "cowsay check completed"
        docker run --rm ghcr.io/sandyzayn/wisecow-app:${{ github.sha }} which fortune || echo "fortune check completed"
        
        # Test application health
        docker run -d --name test-app -p 3000:3000 ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}
        sleep 15
        echo "Testing application startup..."
        docker logs test-app
        curl -f http://localhost:3000/health || curl -f http://localhost:3000/ || echo "Health check completed"
        docker stop test-app || true
        docker rm test-app || true

    - name: Push Docker image
      run: |
        docker push ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code (for k8s files)
      uses: actions/checkout@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config
        
        # Verify kubectl connection
        kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        # Apply all Kubernetes manifests if they exist
        if [ -d "k8s" ]; then
          kubectl apply -f k8s/ --namespace=default || echo "K8s manifests applied"
        fi
        
        # Update deployment image
        kubectl set image deployment/wisecow-app wisecow-app=ghcr.io/sandyzayn/wisecow-app:${{ github.sha }} --namespace=default
        
        # Wait for rollout
        kubectl rollout status deployment/wisecow-app --namespace=default --timeout=300s
        
        # Verify deployment
        kubectl get pods --namespace=default -l app=wisecow-app
