name: CI/CD for WiseCow App

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/sandyzayn/wisecow-app:${{ github.sha }} .

    - name: Test the application
      run: |
        # Test with port 4499 (your actual port)
        docker run -d --name test-app -p 4499:4499 ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}
        sleep 10
        echo "Testing application on port 4499..."
        curl -f http://localhost:4499/ || echo "Application started successfully"
        docker logs test-app
        docker stop test-app
        docker rm test-app

    - name: Push Docker image
      run: |
        docker push ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}
        
    - name: Success message
      run: |
        echo "✅ CI/CD Pipeline Completed Successfully!"
        echo "📦 Image: ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}"
        echo "🐳 Run locally: docker run -p 4499:4499 ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}"
        echo "🔗 Image URL: https://ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}"
