name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sandyzayn/wisecow-app:${{ github.sha }} .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u sandyzayn --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig set image deployment/wisecow-app wisecow-app=ghcr.io/sandyzayn/wisecow-app:${{ github.sha }}
          kubectl --kubeconfig=kubeconfig rollout status deployment/wisecow-app